version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez with purchase price
        columns:
            - name: products_id
              tests:
                - unique
                - not_null
              description: primary key of product, id of each product
            - name: purchase_price
              description: purchase price of each product
      - name: sales
        tests:
          - unique:
              column_name: "(orders_id ||'-'|| pdt_id)"
        identifier: raw_gz_sales
        description: sales of Greenweez, one row per product id in each orders id
        columns:
          - name: date_date
            description: date when the order was made
          - name: orders_id
            description: foreign key for ship, id of the order
          - name: products_id
            description: foreign key for product, id of the product
          - name: revenue
            description: turnover generated by the row
          - name: quantity
            description: quantity of the product in the order
      - name: ship
        identifier: raw_gz_ship
        description: ship informations of each order of Greenweez sales
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
            description: primary key of the table, foreign key for sales, id of the order
          - name: shipping_fee
            description: fee paid by the client for the delivery
          - name: logcost
            description: logistic cost of the order
          - name: ship_cost
            description: shipping cost of the order



models:
  - name: stg_raw_product
  - name: stg_raw_sales
  - name: stg_raw_ship
  - name: int_sales_margin
    description: margin calcultation per order line / product sale
    columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
  - name: int_sales_margin
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - Purchase_cost
            - date_date
            - revenue
            - quantity
  - name: int_orders_margin
    description: margin calcultation per order 
    columns:
      - name: order_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order 
      - name: quantity
        description: sum of quantity per order
  - name: int_orders_operational
    description: operational margin calcultation per order 
    columns:
      - name: operational_margin 
        description: Operational margin = margin + shipping fee - log_cost - ship_cost
  - name: finance_days
    description: finance calculation per days