version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez with purchase price
        columns:
            - name: products_id
              tests:
                - unique
                - not_null
              description: primary key of product, id of each product
            - name: purchase_price
              description: purchase price of each product
      - name: sales
        tests:
          - unique:
              column_name: "(orders_id ||'-'|| pdt_id)"
        identifier: raw_gz_sales
        description: sales of Greenweez, one row per product id in each orders id
        columns:
          - name: date_date
            description: date when the order was made
          - name: orders_id
            description: foreign key for ship, id of the order
          - name: products_id
            description: foreign key for product, id of the product
          - name: revenue
            description: turnover generated by the row
          - name: quantity
            description: quantity of the product in the order
      - name: ship
        identifier: raw_gz_ship
        description: ship informations of each order of Greenweez sales
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
            description: primary key of the table, foreign key for sales, id of the order
          - name: shipping_fee
            description: fee paid by the client for the delivery
          - name: logcost
            description: logistic cost of the order
          - name: ship_cost
            description: shipping cost of the order