version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data
    tables:
      - name: product
        identifier: raw_gz_product
        description: products of Greenweez with purchase price
        columns:
            - name: products_id
              tests:
                - unique
                - not_null
              description: primary key
            - name: purchase_price
              description: purchase price of each product
      - name: sales
        tests:
          - unique:
              column_name: "(orders_id ||'-'|| pdt_id)"
        identifier: raw_gz_sales
        description: sales of Greenweez, one row per product id in each orders id
        columns:
          - name: date_date
            description: date when the order was made
          - name: orders_id
            description: foreign key for ship
          - name: products_id
            description: foreign key for product
          - name: revenue
            description: turnover generated by the row
          - name: quantity
            description: quantity of product in order
      - name: ship
        identifier: raw_gz_ship
        description: ship informations of each order of Greenweez sales
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
            description: primary key,foreign key for sales
          - name: shipping_fee
            description: fee paid 
          - name: logcost
            description: logistic cost of the order
          - name: ship_cost
            description: shipping cost of the order
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords campaigns statistics
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: ad source
          - name: campaign_key
            description: key of campaign
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of session
          - name: impression
            description: nb impressions made
          - name: click
            description: nb of clicks
      - name: bing
        identifier: raw_gz_bing
        description: bing campaigns statistics
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: ad source
          - name: campaign_key
            description: key of campaign
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of session
          - name: impression
            description: nb impressions made
          - name: click
            description: nb of clicks
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo campaigns statistics
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: ad source
          - name: campaign_key
            description: key of campaign
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of session
          - name: impression
            description: nb impressions made
          - name: click
            description: nb of clicks
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook campaigns statistics
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: ad source
          - name: campaign_key
            description: key of campaign
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of session
          - name: impression
            description: nb impressions made
          - name: click
            description: nb of clicks

models:
  - name: stg_raw_product
  - name: stg_raw_sales
  - name: stg_raw_ship
  - name: int_sales_margin
    description: margin calcultation per order line / product sale
    columns:
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
  - name: int_orders_margin
    description: margin calcultation per order 
    columns:
      - name: orders_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order 
      - name: quantity
        description: sum of quantity per order
  - name: int_orders_operational
    description: operational margin calcultation per order 
    columns:
      - name: operational_margin 
        description: Operational margin = margin + shipping fee - log_cost - ship_cost
  - name: finance_days
    description: finance calculation per days
  - name: int_campaigns
    tests:
          - unique:
              column_name: "(date_date ||'-'|| campaign_key)"
    description: aggregation of ads statistics
    columns:
          - name: date_date
            description: date
          - name: paid_source
            description: ad source
          - name: campaign_key
            description: key of campaign
          - name: camPGN_name
            description: name of campaign
          - name: ads_cost
            description: cost of session
          - name: impression
            description: nb impressions made
          - name: click
            description: nb of clicks 
  - name: int_campaigns_days
    description: aggregation by day of ads statistics
    columns:
          - name: date_date
            tests:
              - unique
          - name: ads_cost
          - name: ads_impressions
          - name: ads_clicks
  - name: finance_campaigns_day
    description: finance and ads calculation per day
    columns:
      - name: date_date
        tests:
          - unique
              